version: "3.8"
services:
  web:
    image: labx
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    command: yarn web:start

  server:
    image: labx
    container_name: server
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    command: yarn server:start
